name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run release action
      run: |
        sudo apt-get update
        sudo apt-get install curl build-essential
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220323/llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
        tar xf llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
        rm llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
        PATH=$PWD/llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64/bin:$PATH make
        rm -rf llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.dll"
        token: ${{ secrets.GITHUB_TOKEN }}
